package dev.cypdashuhn.cbg.database

import dev.cypdashuhn.cbg.datapackName
import dev.cypdashuhn.cbg.CustomBlockGroups
import org.bukkit.Bukkit
import org.bukkit.Material
import java.io.File

object DatapackManager {
    fun getDatapackPath(worldName: String): File {
        return CustomBlockGroups.plugin.dataFolder
            .resolve("..") // Navigate up to "plugins"
            .resolve("..") // Navigate up to the server root directory
            .resolve(worldName) // Navigate into the world folder
            .resolve("datapacks") // Go into the datapacks folder
            .resolve("CustomBlockGroups") // Access the specific datapack folder
            .canonicalFile // Resolves the actual path to handle any symbolic links, "..", etc.
    }

    fun modifyDatapackGlobal(action: (File) -> Unit) {
        val worlds = Bukkit.getWorlds().map { it.name }

        worlds.forEach { world ->
            val datapackPath = getDatapackPath(world)
            action(datapackPath)
        }
    }

    val blockFolder: String
        get() {
            val version = Bukkit.getServer().version
            val versionMatch = Regex("""(\d+)\.(\d+)\.(\d+)""").find(version)

            return if (versionMatch != null) {
                val (major, minor, patch) = versionMatch.destructured

                // Convert to integers for comparison
                val majorInt = major.toInt()
                val minorInt = minor.toInt()
                val patchInt = patch.toInt()

                // Check if version is 1.20.5 or higher
                if (majorInt == 1 && minorInt >= 20 && (patchInt >= 5)) {
                    "block"
                } else {
                    "blocks"
                }
            } else {
                "blocks" // Default fallback if version parsing fails
            }
        }


    fun initializeDatapacks() {
        modifyDatapackGlobal { it ->
            val tagsDirectory = it.resolve("data/$datapackName/tags")
            val blocksDirectory = tagsDirectory.resolve(blockFolder)

            blocksDirectory.mkdirs()

            val packMeta = it.resolve("pack.mcmeta")
            if (packMeta.createNewFile()) {
                packMeta.writeText(
                    """
                    {
                        "pack": {
                            "pack_format": 48,
                            "description": "Custom Block Groups! This datapack is generated by the CustomBlockGroups plugin."
                        }
                    }
                    """.trimIndent()
                )
            }
        }
    }

    fun Material.mcTag(): String = "\"minecraft:${this.name.lowercase()}\""

    fun List<Material>.toDatapackDats(): String {
        val valuesList = this.map { it.mcTag() } // Map each material to its Minecraft tag
        return """{"values": $valuesList}""".trimIndent() // Return formatted JSON string
    }

    fun createOrOverrideDatapackEntry(groupName: String, worldName: String, materialList: List<Material>) {
        val datapackPath = getDatapackPath(worldName)
        val tagsDirectory = datapackPath.resolve("data/$datapackName/tags")
        val blocksDirectory = tagsDirectory.resolve(blockFolder)

        val blockFile = blocksDirectory.resolve("$groupName.json")
        if (!blockFile.exists()) {
            blockFile.parentFile.mkdirs()
            blockFile.createNewFile()
        }
        blockFile.writeText(materialList.toDatapackDats())
    }

    fun deleteDatapackEntry(groupName: String, worldName: String) {
        val datapackPath = getDatapackPath(worldName)
        val tagsDirectory = datapackPath.resolve("data/$datapackName/tags")
        val blocksDirectory = tagsDirectory.resolve(blockFolder)
        val itemsDirectory = tagsDirectory.resolve("item")

        val blockFile = blocksDirectory.resolve("$groupName.json")
        blockFile.delete()

        val itemFile = itemsDirectory.resolve("$groupName.json")
        itemFile.delete()
    }
}